#' Synthetic Seurat Test Object for scPairs Examples and Tests
#'
#' @description
#' A minimal synthetic Seurat object with deliberately injected co-expression
#' patterns, intended for use in package examples and unit tests.  The object
#' ships with normalised expression, variable-feature selection, scaled data,
#' a 5-component PCA, and a 2-D UMAP embedding, so it can be passed directly
#' to every scPairs discovery and visualisation function without any additional
#' setup.
#'
#' @format A \code{\link[SeuratObject:Seurat-class]{Seurat}} object with:
#' \describe{
#'   \item{Assay RNA}{
#'     \itemize{
#'       \item \strong{counts}: raw integer count matrix (20 genes × 100 cells).
#'       \item \strong{data}: log-normalised expression matrix.
#'       \item \strong{scale.data}: z-score–scaled matrix for all variable features.
#'     }
#'   }
#'   \item{Reductions}{
#'     \itemize{
#'       \item \strong{pca}: 5-component principal-component embedding.
#'       \item \strong{umap}: 2-D UMAP embedding derived from the top 5 PCs.
#'     }
#'   }
#'   \item{Metadata}{
#'     \itemize{
#'       \item \strong{seurat_clusters}: factor with three balanced cluster
#'         labels (\code{"1"}, \code{"2"}, \code{"3"}).
#'     }
#'   }
#'   \item{Genes}{\code{GENE1}–\code{GENE20} (synthetic gene identifiers).}
#'   \item{Cells}{\code{CELL001}–\code{CELL100}.}
#' }
#'
#' @details
#' Two co-expression patterns are injected at data-generation time:
#' \itemize{
#'   \item \strong{GENE3 & GENE4} — strongly correlated across all 100 cells
#'     (Pearson r ≈ 0.89 in the normalised data).  These are the recommended
#'     genes for discovery and assessment examples.
#'   \item \strong{GENE1 & GENE2} — moderately correlated within cluster 1
#'     only (cluster-specific pattern).
#'   \item All remaining gene pairs are near-independent noise.
#' }
#'
#' The data are generated with a fixed random seed (\code{set.seed(7391)})
#' so the object is fully reproducible.  The generation script is provided
#' in \code{data-raw/make_testdata.R}.
#'
#' @usage data(scpairs_testdata)
#'
#' @family Section_0_Data
#'
#' @seealso \code{\link{FindAllPairs}}, \code{\link{FindGenePairs}},
#'   \code{\link{AssessGenePair}}
#'
#' @source Generated by \code{data-raw/make_testdata.R} with
#'   \code{set.seed(7391)}.
#'
#' @examples
#' # Load and inspect the object
#' data(scpairs_testdata)
#' scpairs_testdata
#'
#' # Verify the injected GENE3 / GENE4 co-expression
#' norm <- SeuratObject::LayerData(scpairs_testdata, layer = "data")
#' cor(as.numeric(norm["GENE3", ]), as.numeric(norm["GENE4", ]))
"scpairs_testdata"
